// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: obJD8bjnvRnfLLVZUByk6i
// Component: Al4HJPuUVlwNVT
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: AJ2OtggAtTstX/component

import { useScreenVariants as useScreenVariantsjbYu71VkK0Cxh7 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: JbYU71vkK0cxh7/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_dark_saa_s_landing_page.module.css"; // plasmic-import: obJD8bjnvRnfLLVZUByk6i/projectcss
import sty from "./PlasmicPriceCard.module.css"; // plasmic-import: Al4HJPuUVlwNVT/css

export type PlasmicPriceCard__VariantMembers = {
  primary: "primary";
  borders: "flatLeft" | "flatRight" | "flatCenter";
};

export type PlasmicPriceCard__VariantsArgs = {
  primary?: SingleBooleanChoiceArg<"primary">;
  borders?: MultiChoiceArg<"flatLeft" | "flatRight" | "flatCenter">;
};

type VariantPropType = keyof PlasmicPriceCard__VariantsArgs;
export const PlasmicPriceCard__VariantProps = new Array<VariantPropType>(
  "primary",
  "borders"
);

export type PlasmicPriceCard__ArgsType = {};
type ArgPropType = keyof PlasmicPriceCard__ArgsType;
export const PlasmicPriceCard__ArgProps = new Array<ArgPropType>();

export type PlasmicPriceCard__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  h4?: p.Flex<"h4">;
  button?: p.Flex<typeof Button>;
};

export interface DefaultPriceCardProps {
  primary?: SingleBooleanChoiceArg<"primary">;
  borders?: MultiChoiceArg<"flatLeft" | "flatRight" | "flatCenter">;
  className?: string;
}

function PlasmicPriceCard__RenderFunc(props: {
  variants: PlasmicPriceCard__VariantsArgs;
  args: PlasmicPriceCard__ArgsType;
  overrides: PlasmicPriceCard__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjbYu71VkK0Cxh7()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [sty.rootborders_flatCenter]: hasVariant(
            variants,
            "borders",
            "flatCenter"
          ),
          [sty.rootborders_flatLeft]: hasVariant(
            variants,
            "borders",
            "flatLeft"
          ),
          [sty.rootborders_flatRight]: hasVariant(
            variants,
            "borders",
            "flatRight"
          ),
          [sty.rootprimary]: hasVariant(variants, "primary", "primary")
        }
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox, {
          [sty.freeBoxborders_flatCenter]: hasVariant(
            variants,
            "borders",
            "flatCenter"
          ),
          [sty.freeBoxborders_flatLeft]: hasVariant(
            variants,
            "borders",
            "flatLeft"
          ),
          [sty.freeBoxborders_flatRight]: hasVariant(
            variants,
            "borders",
            "flatRight"
          ),
          [sty.freeBoxprimary]: hasVariant(variants, "primary", "primary")
        })}
      >
        <h4
          data-plasmic-name={"h4"}
          data-plasmic-override={overrides.h4}
          className={classNames(
            projectcss.all,
            projectcss.h4,
            projectcss.__wab_text,
            sty.h4,
            {
              [sty.h4borders_flatCenter]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.h4borders_flatLeft]: hasVariant(
                variants,
                "borders",
                "flatLeft"
              ),
              [sty.h4borders_flatRight]: hasVariant(
                variants,
                "borders",
                "flatRight"
              )
            }
          )}
        >
          {hasVariant(variants, "borders", "flatRight")
            ? "Enterprise"
            : hasVariant(variants, "borders", "flatLeft")
            ? "Free"
            : "Pro"}
        </h4>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__g5Urz,
            {
              [sty.textborders_flatCenter__g5UrzUjzkI]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.textborders_flatLeft__g5UrZgGxRs]: hasVariant(
                variants,
                "borders",
                "flatLeft"
              ),
              [sty.textborders_flatRight__g5UrzHckRx]: hasVariant(
                variants,
                "borders",
                "flatRight"
              ),
              [sty.textprimary__g5UrzStUT]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            }
          )}
        >
          {hasVariant(variants, "borders", "flatRight")
            ? "Flexible power and security"
            : hasVariant(variants, "borders", "flatLeft")
            ? "A complete analytics platform."
            : "A complete analytics platform."}
        </div>

        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img__llxSw)}
          displayHeight={"auto" as const}
          displayMaxHeight={"none" as const}
          displayMaxWidth={"100%" as const}
          displayMinHeight={"0" as const}
          displayMinWidth={"0" as const}
          displayWidth={"auto" as const}
          loading={"lazy" as const}
          src={{
            src: "/plasmic/dark_saa_s_landing_page/images/linePricingpng.png",
            fullWidth: 300,
            fullHeight: 2,
            aspectRatio: undefined
          }}
        />

        {(hasVariant(globalVariants, "screen", "mobileOnly") ? true : true) ? (
          <div
            className={classNames(projectcss.all, sty.columns__fpOR, {
              [sty.columnsprimary__fpORStUT]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__h6Re)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__nwn5V, {
                  [sty.imgborders_flatLeft__nwn5VgGxRs]: hasVariant(
                    variants,
                    "borders",
                    "flatLeft"
                  )
                })}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"24px" as const}
                loading={"lazy" as const}
                src={
                  hasVariant(variants, "borders", "flatLeft")
                    ? {
                        src: "/plasmic/dark_saa_s_landing_page/images/checklistPricingWhitepng.png",
                        fullWidth: 38,
                        fullHeight: 39,
                        aspectRatio: undefined
                      }
                    : {
                        src: "/plasmic/dark_saa_s_landing_page/images/checklistpng.png",
                        fullWidth: 48,
                        fullHeight: 48,
                        aspectRatio: undefined
                      }
                }
              />
            </div>

            <div
              className={classNames(projectcss.all, sty.column__aG150, {
                [sty.columnborders_flatRight__aG150HckRx]: hasVariant(
                  variants,
                  "borders",
                  "flatRight"
                )
              })}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__c7VUo,
                  {
                    [sty.textborders_flatLeft__c7VUOgGxRs]: hasVariant(
                      variants,
                      "borders",
                      "flatLeft"
                    ),
                    [sty.textborders_flatRight__c7VUoHckRx]: hasVariant(
                      variants,
                      "borders",
                      "flatRight"
                    ),
                    [sty.textprimary__c7VUoStUT]: hasVariant(
                      variants,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {hasVariant(variants, "borders", "flatRight")
                  ? "Everything in pro"
                  : hasVariant(variants, "borders", "flatLeft")
                  ? "1 Product"
                  : "Up to 10 projects"}
              </div>
            </div>
          </div>
        ) : null}

        {(
          hasVariant(variants, "borders", "flatCenter")
            ? true
            : hasVariant(variants, "primary", "primary")
            ? true
            : true
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns__glYih, {
              [sty.columnsborders_flatCenter__glYihUjzkI]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.columnsborders_flatLeft__glYihgGxRs]: hasVariant(
                variants,
                "borders",
                "flatLeft"
              ),
              [sty.columnsborders_flatRight__glYihHckRx]: hasVariant(
                variants,
                "borders",
                "flatRight"
              ),
              [sty.columnsprimary__glYihStUT]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__k8KcU)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___0Q7MR, {
                  [sty.imgborders_flatLeft___0Q7MRgGxRs]: hasVariant(
                    variants,
                    "borders",
                    "flatLeft"
                  )
                })}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"24px" as const}
                loading={"lazy" as const}
                src={
                  hasVariant(variants, "borders", "flatLeft")
                    ? {
                        src: "/plasmic/dark_saa_s_landing_page/images/checklistPricingWhitepng.png",
                        fullWidth: 38,
                        fullHeight: 39,
                        aspectRatio: undefined
                      }
                    : {
                        src: "/plasmic/dark_saa_s_landing_page/images/checklistpng.png",
                        fullWidth: 48,
                        fullHeight: 48,
                        aspectRatio: undefined
                      }
                }
              />
            </div>

            <div className={classNames(projectcss.all, sty.column___3Zv4X)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sTcC6,
                  {
                    [sty.textborders_flatCenter__sTcC6UjzkI]: hasVariant(
                      variants,
                      "borders",
                      "flatCenter"
                    ),
                    [sty.textborders_flatLeft__sTcC6GGxRs]: hasVariant(
                      variants,
                      "borders",
                      "flatLeft"
                    ),
                    [sty.textborders_flatRight__sTcC6HckRx]: hasVariant(
                      variants,
                      "borders",
                      "flatRight"
                    ),
                    [sty.textprimary__sTcC6StUT]: hasVariant(
                      variants,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {hasVariant(variants, "borders", "flatRight")
                  ? "Volume discount"
                  : hasVariant(variants, "borders", "flatLeft")
                  ? "Analytics board"
                  : hasVariant(variants, "primary", "primary")
                  ? "Analytics board"
                  : "Up to 10 projects"}
              </div>
            </div>
          </div>
        ) : null}

        {(
          hasVariant(variants, "borders", "flatCenter")
            ? true
            : hasVariant(variants, "borders", "flatLeft")
            ? true
            : hasVariant(variants, "primary", "primary")
            ? true
            : hasVariant(globalVariants, "screen", "mobileOnly")
            ? true
            : true
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns___3AHMe, {
              [sty.columnsborders_flatCenter___3AHMeUjzkI]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.columnsborders_flatLeft___3AHMegGxRs]: hasVariant(
                variants,
                "borders",
                "flatLeft"
              ),
              [sty.columnsprimary___3AHMeStUT]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__npS5D)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__jUdl, {
                  [sty.imgborders_flatLeft__jUdlGGxRs]: hasVariant(
                    variants,
                    "borders",
                    "flatLeft"
                  )
                })}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"24px" as const}
                loading={"lazy" as const}
                src={
                  hasVariant(variants, "borders", "flatLeft")
                    ? {
                        src: "/plasmic/dark_saa_s_landing_page/images/checklistPricingWhitepng.png",
                        fullWidth: 38,
                        fullHeight: 39,
                        aspectRatio: undefined
                      }
                    : {
                        src: "/plasmic/dark_saa_s_landing_page/images/checklistpng.png",
                        fullWidth: 48,
                        fullHeight: 48,
                        aspectRatio: undefined
                      }
                }
              />
            </div>

            <div
              className={classNames(projectcss.all, sty.column__cU7Yt, {
                [sty.columnborders_flatLeft__cU7YtgGxRs]: hasVariant(
                  variants,
                  "borders",
                  "flatLeft"
                ),
                [sty.columnborders_flatRight__cU7YtHckRx]: hasVariant(
                  variants,
                  "borders",
                  "flatRight"
                ),
                [sty.columnprimary__cU7YtStUT]: hasVariant(
                  variants,
                  "primary",
                  "primary"
                )
              })}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bVrG,
                  {
                    [sty.textborders_flatLeft__bVrGgGxRs]: hasVariant(
                      variants,
                      "borders",
                      "flatLeft"
                    ),
                    [sty.textprimary__bVrGStUT]: hasVariant(
                      variants,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {hasVariant(variants, "borders", "flatLeft")
                  ? "Insights panel"
                  : hasVariant(variants, "primary", "primary")
                  ? "Analytics board"
                  : "Up to 10 projects"}
              </div>
            </div>

            {(
              hasVariant(variants, "borders", "flatRight")
                ? true
                : hasVariant(variants, "borders", "flatLeft")
                ? true
                : hasVariant(variants, "primary", "primary")
                ? true
                : hasVariant(globalVariants, "screen", "mobileOnly")
                ? true
                : true
            ) ? (
              <div
                className={classNames(projectcss.all, sty.column__wNp8J, {
                  [sty.columnborders_flatLeft__wNp8JgGxRs]: hasVariant(
                    variants,
                    "borders",
                    "flatLeft"
                  ),
                  [sty.columnborders_flatRight__wNp8JHckRx]: hasVariant(
                    variants,
                    "borders",
                    "flatRight"
                  ),
                  [sty.columnprimary__wNp8JStUT]: hasVariant(
                    variants,
                    "primary",
                    "primary"
                  )
                })}
              />
            ) : null}
          </div>
        ) : null}

        {(
          hasVariant(variants, "borders", "flatCenter")
            ? true
            : hasVariant(variants, "borders", "flatLeft")
            ? true
            : hasVariant(variants, "primary", "primary")
            ? true
            : hasVariant(globalVariants, "screen", "mobileOnly")
            ? true
            : false
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns__eiUP, {
              [sty.columnsborders_flatCenter__eiUPUjzkI]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.columnsborders_flatLeft__eiUPgGxRs]: hasVariant(
                variants,
                "borders",
                "flatLeft"
              ),
              [sty.columnsprimary__eiUPStUT]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__zz4X)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___248TA, {
                  [sty.imgborders_flatLeft___248TAgGxRs]: hasVariant(
                    variants,
                    "borders",
                    "flatLeft"
                  )
                })}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"24px" as const}
                loading={"lazy" as const}
                src={
                  hasVariant(variants, "borders", "flatLeft")
                    ? {
                        src: "/plasmic/dark_saa_s_landing_page/images/checklistPricingWhitepng.png",
                        fullWidth: 38,
                        fullHeight: 39,
                        aspectRatio: undefined
                      }
                    : {
                        src: "/plasmic/dark_saa_s_landing_page/images/checklistpng.png",
                        fullWidth: 48,
                        fullHeight: 48,
                        aspectRatio: undefined
                      }
                }
              />
            </div>

            <div className={classNames(projectcss.all, sty.column__kzWO)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4ZhI,
                  {
                    [sty.textborders_flatLeft___4ZhIgGxRs]: hasVariant(
                      variants,
                      "borders",
                      "flatLeft"
                    ),
                    [sty.textprimary___4ZhIStUT]: hasVariant(
                      variants,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {hasVariant(variants, "borders", "flatLeft")
                  ? "CLI access"
                  : hasVariant(variants, "primary", "primary")
                  ? "Analytics board"
                  : "Up to 10 projects"}
              </div>
            </div>
          </div>
        ) : null}

        {(
          hasVariant(variants, "borders", "flatCenter")
            ? true
            : hasVariant(variants, "primary", "primary")
            ? true
            : false
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns__e67X, {
              [sty.columnsborders_flatCenter__e67XUjzkI]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.columnsprimary__e67XStUT]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__bqQl8)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__bSxO)}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"24px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/dark_saa_s_landing_page/images/checklistpng.png",
                  fullWidth: 48,
                  fullHeight: 48,
                  aspectRatio: undefined
                }}
              />
            </div>

            <div className={classNames(projectcss.all, sty.column__opxp1)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bUqqK,
                  {
                    [sty.textborders_flatCenter__bUqqKUjzkI]: hasVariant(
                      variants,
                      "borders",
                      "flatCenter"
                    ),
                    [sty.textprimary__bUqqKStUT]: hasVariant(
                      variants,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {"Insights panel"}
              </div>
            </div>
          </div>
        ) : null}

        {(
          hasVariant(variants, "borders", "flatCenter")
            ? true
            : hasVariant(variants, "primary", "primary")
            ? true
            : false
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns___4B93, {
              [sty.columnsborders_flatCenter___4B93UjzkI]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.columnsprimary___4B93StUT]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column___2Hdg7)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___3Pf14)}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("16px" as const)
                    : ("24px" as const)
                }
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/dark_saa_s_landing_page/images/checklistpng.png",
                  fullWidth: 48,
                  fullHeight: 48,
                  aspectRatio: undefined
                }}
              />
            </div>

            <div className={classNames(projectcss.all, sty.column__xkllc)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kgHy,
                  {
                    [sty.textprimary__kgHyStUT]: hasVariant(
                      variants,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {"CLI access"}
              </div>
            </div>
          </div>
        ) : null}

        {(
          hasVariant(variants, "borders", "flatCenter")
            ? true
            : hasVariant(variants, "primary", "primary")
            ? true
            : false
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns__groDt, {
              [sty.columnsborders_flatCenter__groDtUjzkI]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.columnsprimary__groDtStUT]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__eVxqg)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__rjs1O)}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"24px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/dark_saa_s_landing_page/images/checklistpng.png",
                  fullWidth: 48,
                  fullHeight: 48,
                  aspectRatio: undefined
                }}
              />
            </div>

            <div className={classNames(projectcss.all, sty.column__dAiQ)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__c9D2O,
                  {
                    [sty.textprimary__c9D2OStUT]: hasVariant(
                      variants,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {"Automation features"}
              </div>
            </div>
          </div>
        ) : null}

        {(
          hasVariant(variants, "borders", "flatCenter")
            ? true
            : hasVariant(variants, "primary", "primary")
            ? true
            : false
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns___0KR5Q, {
              [sty.columnsborders_flatCenter___0KR5QUjzkI]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.columnsprimary___0KR5QStUT]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__ryOmT)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__vXb)}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"24px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/dark_saa_s_landing_page/images/checklistpng.png",
                  fullWidth: 48,
                  fullHeight: 48,
                  aspectRatio: undefined
                }}
              />
            </div>

            <div className={classNames(projectcss.all, sty.column___05YW9)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__emN3E,
                  {
                    [sty.textprimary__emN3EStUT]: hasVariant(
                      variants,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {"Team features"}
              </div>
            </div>
          </div>
        ) : null}

        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img___4OzwV)}
          displayHeight={"auto" as const}
          displayMaxHeight={"none" as const}
          displayMaxWidth={"100%" as const}
          displayMinHeight={"0" as const}
          displayMinWidth={"0" as const}
          displayWidth={"auto" as const}
          loading={"lazy" as const}
          src={{
            src: "/plasmic/dark_saa_s_landing_page/images/linePricingpng.png",
            fullWidth: 300,
            fullHeight: 2,
            aspectRatio: undefined
          }}
        />

        {(
          hasVariant(variants, "borders", "flatCenter")
            ? true
            : hasVariant(variants, "borders", "flatRight")
            ? true
            : hasVariant(variants, "borders", "flatLeft")
            ? true
            : false
        ) ? (
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___8H7Np,
              {
                [sty.textborders_flatCenter___8H7NpUjzkI]: hasVariant(
                  variants,
                  "borders",
                  "flatCenter"
                ),
                [sty.textborders_flatLeft___8H7NpgGxRs]: hasVariant(
                  variants,
                  "borders",
                  "flatLeft"
                ),
                [sty.textborders_flatRight___8H7NpHckRx]: hasVariant(
                  variants,
                  "borders",
                  "flatRight"
                )
              }
            )}
          >
            {hasVariant(variants, "borders", "flatCenter")
              ? "$ 50"
              : hasVariant(variants, "borders", "flatRight")
              ? "$ 800"
              : "$ 0"}
          </div>
        ) : null}

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__oe5,
            {
              [sty.textborders_flatCenter__oe5UjzkI]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.textborders_flatLeft__oe5GGxRs]: hasVariant(
                variants,
                "borders",
                "flatLeft"
              ),
              [sty.textborders_flatRight__oe5HckRx]: hasVariant(
                variants,
                "borders",
                "flatRight"
              )
            }
          )}
        >
          {hasVariant(variants, "borders", "flatRight")
            ? "Starting price, customizable"
            : hasVariant(variants, "borders", "flatLeft")
            ? "Free Forever"
            : "per project/month"}
        </div>

        {(
          hasVariant(variants, "borders", "flatRight")
            ? true
            : hasVariant(variants, "borders", "flatLeft")
            ? true
            : true
        ) ? (
          <Button
            data-plasmic-name={"button"}
            data-plasmic-override={overrides.button}
            className={classNames("__wab_instance", sty.button, {
              [sty.buttonborders_flatCenter]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.buttonborders_flatLeft]: hasVariant(
                variants,
                "borders",
                "flatLeft"
              ),
              [sty.buttonborders_flatRight]: hasVariant(
                variants,
                "borders",
                "flatRight"
              ),
              [sty.buttonprimary]: hasVariant(variants, "primary", "primary")
            })}
            color={
              hasVariant(variants, "borders", "flatLeft")
                ? ("white" as const)
                : ("blue" as const)
            }
            endIcon={
              <svg
                className={classNames(projectcss.all, sty.svg__dscZ)}
                role={"img"}
              />
            }
            link={"#" as const}
            startIcon={
              <svg
                className={classNames(projectcss.all, sty.svg__dwxfA)}
                role={"img"}
              />
            }
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bvEy4,
                {
                  [sty.textborders_flatCenter__bvEy4UjzkI]: hasVariant(
                    variants,
                    "borders",
                    "flatCenter"
                  ),
                  [sty.textborders_flatLeft__bvEy4GGxRs]: hasVariant(
                    variants,
                    "borders",
                    "flatLeft"
                  ),
                  [sty.textborders_flatRight__bvEy4HckRx]: hasVariant(
                    variants,
                    "borders",
                    "flatRight"
                  )
                }
              )}
            >
              {hasVariant(variants, "borders", "flatCenter")
                ? "Go Become pro"
                : hasVariant(variants, "borders", "flatRight")
                ? "Everything is yours"
                : hasVariant(variants, "borders", "flatLeft")
                ? "Claim Free"
                : "Go Become pro"}
            </div>
          </Button>
        ) : null}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "h4", "button"],
  freeBox: ["freeBox", "h4", "button"],
  h4: ["h4"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  h4: "h4";
  button: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPriceCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPriceCard__VariantsArgs;
    args?: PlasmicPriceCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPriceCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPriceCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicPriceCard__ArgProps,
          internalVariantPropNames: PlasmicPriceCard__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicPriceCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPriceCard";
  } else {
    func.displayName = `PlasmicPriceCard.${nodeName}`;
  }
  return func;
}

export const PlasmicPriceCard = Object.assign(
  // Top-level PlasmicPriceCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    h4: makeNodeComponent("h4"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicPriceCard
    internalVariantProps: PlasmicPriceCard__VariantProps,
    internalArgProps: PlasmicPriceCard__ArgProps
  }
);

export default PlasmicPriceCard;
/* prettier-ignore-end */
